### ISSUE TITLE
Favorite Screen Layout

### ISSUE THREAD

**Issue by sefath13** [codepath-group6/restaurant#14]
Create new tab bar to show favorite screen, which would pop up a new screen to show favorites

**Comment by sefath13** [comment]
Eugene took a stab at creating the favorites page but ran into these issues: 
- FavoritesViewController.swift has the code for the tableView.dataSource and tableView.delegate
- TableView is not being populated.
- restaurantsArray[currentIndex-2] changed to currentIndex-3 in FeedViewController.swift under
    extension FeedViewController: KolodaViewDelegate {}

**Comment by SYee50** [comment]
- Table view populating with restaurant name and image
- Restaurants without an image url in Parse do not have an image next to them
![Name_and_image](https://user-images.githubusercontent.com/102485385/199796491-745ba133-ac80-45b3-8fee-c9023ee1a900.gif)

**Comment by SYee50** [comment]
Issues:

- Image for restaurant with image url saved in Parse showing up on other restaurant's table cells after dragging down (error disappears if you exit and reenter favorites page)
- Favorites page populating with favorited restaurants from all users

![Images_duplicating_when_refreshed?](https://user-images.githubusercontent.com/102485385/199797544-6774ab59-09ee-4315-b202-c122d0c57f02.gif)

**Comment by EugenSong** [comment]
Favorite list is mapped to current user. 

On some runs, restaurant images are not rendered. Can be fixed by pulling down to refresh or leaving Favorites List and then coming back. 

<img src= "https://user-images.githubusercontent.com/75242911/199850614-e0bf5da4-8c77-4392-8d6e-a0fa4149212e.gif" width=50% height=50%\>

**Comment by sefath13** [comment]
newer constraint edits to favorites page

<img width="319" alt="Screen Shot 2022-11-04 at 3 30 32 PM" src="https://user-images.githubusercontent.com/74398530/200087514-290fbbe6-75d4-4566-beb6-d626ba285a48.png">
