### ISSUE TITLE
Adding spoons to represent like/dislike

### ISSUE THREAD

**Issue by sefath13** [codepath-group6/restaurant#19]
Show spoons as the 2 spoons that we have on launch screen 

When someone clicks 'like', or swipe right, favorites restaurant similar to Parstagram comments. 

Save restaurant id https://www.yelp.com/developers/documentation/v3/business

**Comment by LaUrrego** [comment]
spoon button graphics added, awaiting feedback from team.

**Comment by LaUrrego** [comment]
Updated button layout per feedback, and implemented saving of unique restaurant id in Parse when swiping right or clicking the right spoon button.
