### ISSUE TITLE
Login Screen View Controller + Layout

### ISSUE THREAD

**Issue by sefath13** [codepath-group6/restaurant#2]
When user opens app and after seeing launch screen, user will see login screen with: 
- FUUD logo
- username text field
- password text field
- signin button
- sign up button

Set up Parse server

**Comment by SYee50** [comment]
Currently, the user opens the app and sees the login/signup screen. After signup or login the screen segues to a blank screen.

Parse server is set up.
![SignupLogin](https://user-images.githubusercontent.com/102485385/198130013-e8c34116-b6e4-4e4d-9e6f-bda0100099bd.gif)
