### ISSUE TITLE
spacing issue with manual location

### ISSUE THREAD

**Issue by sefath13** [codepath-group6/restaurant#40]
dismiss feature on manual location 
spacing issue when user inputs manual location

**Comment by EugenSong** [comment]
spacing issue when user inputs manual location - resolved by Sandra

**Comment by sefath13** [comment]
whoops! reopening because dismiss feature is still being worked on

**Comment by SYee50** [comment]
Dismiss feature on manual location completed.
Skip button added to LocationViewController.
