### ISSUE TITLE
Restaurant Detail Screen Layout

### ISSUE THREAD

**Issue by sefath13** [codepath-group6/restaurant#5]
Add tap gesture to ImageView on Restaurant which would trigger detail screen:
- Restaurant Name
- Address
- Phone
- Reviews
- Cuisine Type

**Comment by sefath13** [comment]
Don't need to implement API, just add layout and placeholder text

**Comment by ken-steckler** [comment]
Created a new view controller that will open modally when thumbs up is pressed. Still have to figure out how to pass data from the swipe screen to the new view controller.
