### ISSUE TITLE
Polish and Finalize App

### ISSUE THREAD

**Issue by LaUrrego** [codepath-group6/restaurant#57]
Await feedback to add the finishing touches to the app to take it to home stretch

**Comment by sefath13** [comment]
i just added some labels to the vid walkthroughs to differentiate build progress, but besides that I think we are good to submit!

**Comment by sefath13** [comment]
I changed the layout of our readme as a more finalized product
I also added our final demo vid and a demo gif, feel free to replace it with a better looking one
I added our what's next section at the bottom, I was thinking it should be before our completed user stories but I'm not sure
